EXTRA_CFLAGS := -I$(TOPDIR)/fs/grub -I$(TOPDIR)/fs/fatx -I$(TOPDIR)/lib/crypt -I$(TOPDIR)/drivers/cpu -I$(TOPDIR)/drivers/ide #-I$(TOPDIR)/drivers/flash 

O_TARGET := BootResetAction.o
#  BootStartup.o
include $(TOPDIR)/Rules.make
