EXTRA_CFLAGS := -I$(TOPDIR)/fs/grub -I$(TOPDIR)/fs/fatx -I$(TOPDIR)/lib/crypt -I$(TOPDIR)/drivers/cpu -I$(TOPDIR)/drivers/ide #-I$(TOPDIR)/drivers/flash 

O_TARGET := LoadLinux.o BootStartup.o BootResetAction.o

include $(TOPDIR)/Rules.make
