EXTRA_CFLAGS := -mpreferred-stack-boundary=2
#-funroll-loops -I$(TOPDIR)/lib/crypt

O_TARGET := 2bBootStartBios.o 2bPicResponseAction.o \
    2bBootLibrary.o
		
#  2bBootStartup.o 

include $(TOPDIR)/Rules.make
